In [6]:
import pandas as pd

In [7]:
genetic_data = pd.read_csv("output/genetic_vs_3.csv")

In [11]:
genetic_data["player 1"].value_counts()

player 1
{'apertura': {'corner': 0.1141, 'mob': 0.6328, 'stable': 0.3379, 'parity': 0.9211, 'pos': 0.102}, 'medio': {'corner': 0.8077, 'mob': 0.5559, 'stable': 0.6918342811648904, 'parity': 0.4097, 'pos': 0.3183}, 'final': {'corner': 0.1662, 'mob': 0.831, 'stable': 0.4163, 'parity': 0.5333, 'pos': 0.6764}}      10
{'apertura': {'corner': 0.4033, 'mob': 0.4844, 'stable': 0.4534, 'parity': 0.7111, 'pos': 0.3628}, 'medio': {'corner': 0.4561, 'mob': 0.7731, 'stable': 0.8084, 'parity': 0.8716, 'pos': 0.2125}, 'final': {'corner': 0.2062, 'mob': 0.6556, 'stable': 0.236, 'parity': 0.5923, 'pos': 0.7982}}                  7
{'apertura': {'corner': 0.0806, 'mob': 0.3481, 'stable': 0.6498, 'parity': 0.9519, 'pos': 0.0583}, 'medio': {'corner': 0.6825, 'mob': 0.9393, 'stable': 0.8581, 'parity': 0.8179, 'pos': 0.2365}, 'final': {'corner': 0.0209, 'mob': 0.9103, 'stable': 0.3316, 'parity': 0.457, 'pos': 0.9795}}                  7
{'apertura': {'corner': 0.4476, 'mob': 0.5625, 'stable': 0.5173, 'parity': 0.703, 'pos': 0.4945}, 'medio': {'corner': 0.5076, 'mob': 0.7525, 'stable': 0.7384, 'parity': 0.7029, 'pos': 0.2642}, 'final': {'corner': 0.2708, 'mob': 0.6765, 'stable': 0.3178, 'parity': 0.6343, 'pos': 0.7185}}                  5
{'apertura': {'corner': 0.3978, 'mob': 0.6408888877450305, 'stable': 0.6793, 'parity': 0.7959, 'pos': 0.5273}, 'medio': {'corner': 0.7051, 'mob': 0.7947, 'stable': 0.5734, 'parity': 0.4512, 'pos': 0.3627}, 'final': {'corner': 0.1907, 'mob': 0.7559, 'stable': 0.5457, 'parity': 0.5983, 'pos': 0.5424}}     5
                                                                                                                                                                                                                                                                                                                ..
{'apertura': {'corner': 0.4305, 'mob': 0.6091, 'stable': 0.544, 'parity': 0.6817991026263007, 'pos': 0.4964}, 'medio': {'corner': 0.5938, 'mob': 0.7514, 'stable': 0.6734, 'parity': 0.5938, 'pos': 0.3225}, 'final': {'corner': 0.2487, 'mob': 0.7058, 'stable': 0.4011, 'parity': 0.6161, 'pos': 0.6473}}      1
{'apertura': {'corner': 0.3440358390046701, 'mob': 0.5697, 'stable': 0.5035, 'parity': 0.796, 'pos': 0.3667}, 'medio': {'corner': 0.6041, 'mob': 0.735, 'stable': 0.7143, 'parity': 0.6341, 'pos': 0.2982}, 'final': {'corner': 0.2032, 'mob': 0.7413, 'stable': 0.3728, 'parity': 0.5843, 'pos': 0.7064}}       1
{'apertura': {'corner': 0.3805, 'mob': 0.6171, 'stable': 0.5533, 'parity': 0.8004, 'pos': 0.4522}, 'medio': {'corner': 0.6605, 'mob': 0.7464, 'stable': 0.6494, 'parity': 0.567, 'pos': 0.3542}, 'final': {'corner': 0.2042, 'mob': 0.7476, 'stable': 0.4455, 'parity': 0.5939, 'pos': 0.6304}}                  1
{'apertura': {'corner': 0.3789, 'mob': 0.6148, 'stable': 0.6179, 'parity': 0.8005, 'pos': 0.4713}, 'medio': {'corner': 0.672, 'mob': 0.7787, 'stable': 0.6258, 'parity': 0.5281, 'pos': 0.3397}, 'final': {'corner': 0.1918, 'mob': 0.7509, 'stable': 0.482, 'parity': 0.592, 'pos': 0.6047}}                    1
{'apertura': {'corner': 0.4734127283646897, 'mob': 0.6671, 'stable': 0.5719, 'parity': 0.7854, 'pos': 0.5}, 'medio': {'corner': 0.7029, 'mob': 0.731, 'stable': 0.5948, 'parity': 0.4864, 'pos': 0.3567}, 'final': {'corner': 0.2099, 'mob': 0.7515, 'stable': 0.5037, 'parity': 0.6015, 'pos': 0.5608}}         1
Name: count, Length: 95, dtype: int64

In [ ]:
# weights 4
genetic_data[genetic_data["player 1"] == "{'apertura': {'corner': 0.1141, 'mob': 0.6328, 'stable': 0.3379, 'parity': 0.9211, 'pos': 0.102}, 'medio': {'corner': 0.8077, 'mob': 0.5559, 'stable': 0.6918342811648904, 'parity': 0.4097, 'pos': 0.3183}, 'final': {'corner': 0.1662, 'mob': 0.831, 'stable': 0.4163, 'parity': 0.5333, 'pos': 0.6764}}"]

,player 1,player 2,winner,winner points,Total_points,depth,epocs
25,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",heuristic_2,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",49.0,64,60,2
32,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",bad_player,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",47.0,61,59,3
48,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",minimax_base,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",43.0,64,61,4
68,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",random,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",49.0,64,64,5
80,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",greedy,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",47.0,64,60,6
111,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",heuristic_2,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",40.0,64,60,7
112,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",bad_player,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",47.0,61,59,8
135,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",minimax_base,minimax_base,40.0,64,60,9
150,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",random,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",47.0,62,59,10
164,"{'apertura': {'corner': 0.1141, 'mob': 0.6328,...",greedy,greedy,48.0,59,60,11

In [ ]:
# weights 5
genetic_data[genetic_data["player 1"] == "{'apertura': {'corner': 0.4033, 'mob': 0.4844, 'stable': 0.4534, 'parity': 0.7111, 'pos': 0.3628}, 'medio': {'corner': 0.4561, 'mob': 0.7731, 'stable': 0.8084, 'parity': 0.8716, 'pos': 0.2125}, 'final': {'corner': 0.2062, 'mob': 0.6556, 'stable': 0.236, 'parity': 0.5923, 'pos': 0.7982}}"]

,player 1,player 2,winner,winner points,Total_points,depth,epocs
29,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",heuristic_2,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",42.0,64,61,2
34,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",bad_player,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",36.0,64,60,3
51,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",minimax_base,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",34.0,64,63,4
64,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",random,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",49.0,49,53,5
86,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",greedy,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",35.0,63,60,6
105,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",heuristic_2,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",39.0,64,61,7
118,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",bad_player,"{'apertura': {'corner': 0.4033, 'mob': 0.4844,...",41.0,64,62,8

In [ ]:
# weights 6
genetic_data[genetic_data["player 1"] == "{'apertura': {'corner': 0.0806, 'mob': 0.3481, 'stable': 0.6498, 'parity': 0.9519, 'pos': 0.0583}, 'medio': {'corner': 0.6825, 'mob': 0.9393, 'stable': 0.8581, 'parity': 0.8179, 'pos': 0.2365}, 'final': {'corner': 0.0209, 'mob': 0.9103, 'stable': 0.3316, 'parity': 0.457, 'pos': 0.9795}}"]

,player 1,player 2,winner,winner points,Total_points,depth,epocs
4,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",greedy,NaN,NaN,62,60,1
16,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",heuristic_2,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",52.0,62,61,2
41,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",bad_player,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",41.0,64,60,3
52,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",minimax_base,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",47.0,63,60,4
66,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",random,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",52.0,61,60,5
83,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",greedy,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",41.0,64,60,6
103,"{'apertura': {'corner': 0.0806, 'mob': 0.3481,...",heuristic_2,heuristic_2,50.0,64,61,7